# Evaluate code

In [28]:
from code_agent.creat_react_code_agent.code_agent_react import CodeAgentReact
from langsmith import evaluate, aevaluate

import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

## Criando dataset no LangSmith

In [29]:
from datasets import load_dataset
from tqdm import tqdm

human_eval = load_dataset("openai_humaneval")['test']

data_set_code_langsmith = []
for problem in tqdm(human_eval, desc="Problems", unit="problem"):
    prompt = problem['prompt']
    test_code = problem['test']
    
    dict_data = {
      "inputs": {"aswer_code": prompt},
      "outputs": {"response_code": test_code},
  }
    
   
    data_set_code_langsmith.append(dict_data)

Problems: 100%|██████████| 164/164 [00:00<00:00, 9150.56problem/s]

In [30]:
from langsmith import Client

client_langsmith = Client()


tamanho_amostra = 5

dataset_name = f"Human-Eval-Code-{tamanho_amostra}-aleatorios"

import random
data_aleatorios = []
index_aleatorios = random.sample(range(len(data_set_code_langsmith)), tamanho_amostra)
for index in index_aleatorios:
    data_aleatorios.append(data_set_code_langsmith[index])


# Create dataset if it doesn't exist
if not client_langsmith.has_dataset(dataset_name=dataset_name):
    dataset = client_langsmith.create_dataset(
        dataset_name=dataset_name, 
        description="The HumanEval dataset released by OpenAI includes 164 programming problems with a function sig- nature, docstring, body, and several unit tests. They were handwritten to ensure not to be included in the training set of code generation models."
    )
    
    client_langsmith.create_examples(dataset_id=dataset.id, examples=data_aleatorios)

In [31]:
data_aleatorios

[{'inputs': {'aswer_code': '\ndef cycpattern_check(a , b):\n    """You are given 2 words. You need to return True if the second word or any of its rotations is a substring in the first word\n    cycpattern_check("abcd","abd") => False\n    cycpattern_check("hello","ell") => True\n    cycpattern_check("whassup","psus") => False\n    cycpattern_check("abab","baa") => True\n    cycpattern_check("efef","eeff") => False\n    cycpattern_check("himenss","simen") => True\n\n    """\n'},
  'outputs': {'response_code': 'def check(candidate):\n\n    # Check some simple cases\n    #assert True, "This prints if this assert fails 1 (good for debugging!)"\n\n    # Check some edge cases that are easy to work out by hand.\n    #assert True, "This prints if this assert fails 2 (also good for debugging!)"\n    assert  candidate("xyzw","xyw") == False , "test #0"\n    assert  candidate("yello","ell") == True , "test #1"\n    assert  candidate("whattup","ptut") == False , "test #2"\n    assert  candidate("efef","fee") == True , "test #3"\n    assert  candidate("abab","aabb") == False , "test #4"\n    assert  candidate("winemtt","tinem") == True , "test #5"\n\n'}},
 {'inputs': {'aswer_code': "\ndef double_the_difference(lst):\n    '''\n    Given a list of numbers, return the sum of squares of the numbers\n    in the list that are odd. Ignore numbers that are negative or not integers.\n    \n    double_the_difference([1, 3, 2, 0]) == 1 + 9 + 0 + 0 = 10\n    double_the_difference([-1, -2, 0]) == 0\n    double_the_difference([9, -2]) == 81\n    double_the_difference([0]) == 0  \n   \n    If the input list is empty, return 0.\n    '''\n"},
  'outputs': {'response_code': 'def check(candidate):\n\n    # Check some simple cases\n    assert candidate([]) == 0 , "This prints if this assert fails 1 (good for debugging!)"\n    assert candidate([5, 4]) == 25 , "This prints if this assert fails 2 (good for debugging!)"\n    assert candidate([0.1, 0.2, 0.3]) == 0 , "This prints if this assert fails 3 (good for debugging!)"\n    assert candidate([-10, -20, -30]) == 0 , "This prints if this assert fails 4 (good for debugging!)"\n\n\n    # Check some edge cases that are easy to work out by hand.\n    assert candidate([-1, -2, 8]) == 0, "This prints if this assert fails 5 (also good for debugging!)"\n    assert candidate([0.2, 3, 5]) == 34, "This prints if this assert fails 6 (also good for debugging!)"\n    lst = list(range(-99, 100, 2))\n    odd_sum = sum([i**2 for i in lst if i%2!=0 and i > 0])\n    assert candidate(lst) == odd_sum , "This prints if this assert fails 7 (good for debugging!)"\n\n'}},
 {'inputs': {'aswer_code': '\n\ndef unique(l: list):\n    """Return sorted unique elements in a list\n    >>> unique([5, 3, 5, 2, 3, 3, 9, 0, 123])\n    [0, 2, 3, 5, 9, 123]\n    """\n'},
  'outputs': {'response_code': '\n\nMETADATA = {}\n\n\ndef check(candidate):\n    assert candidate([5, 3, 5, 2, 3, 3, 9, 0, 123]) == [0, 2, 3, 5, 9, 123]\n\n'}},
 {'inputs': {'aswer_code': '\ndef is_equal_to_sum_even(n):\n    """Evaluate whether the given number n can be written as the sum of exactly 4 positive even numbers\n    Example\n    is_equal_to_sum_even(4) == False\n    is_equal_to_sum_even(6) == False\n    is_equal_to_sum_even(8) == True\n    """\n'},
  'outputs': {'response_code': 'def check(candidate):\n    assert candidate(4) == False\n    assert candidate(6) == False\n    assert candidate(8) == True\n    assert candidate(10) == True\n    assert candidate(11) == False\n    assert candidate(12) == True\n    assert candidate(13) == False\n    assert candidate(16) == True\n'}},
 {'inputs': {'aswer_code': '\n\ndef fib4(n: int):\n    """The Fib4 number sequence is a sequence similar to the Fibbonacci sequnece that\'s defined as follows:\n    fib4(0) -> 0\n    fib4(1) -> 0\n    fib4(2) -> 2\n    fib4(3) -> 0\n    fib4(n) -> fib4(n-1) + fib4(n-2) + fib4(n-3) + fib4(n-4).\n    Please write a function to efficiently compute the n-th element of the fib4 number sequence.  Do not use recursion.\n    >>> fib4(5)\n    4\n    >>> fib4(6)\n    8\n    >>> fib4(7)\n    14\n    """\n'},
  'outputs': {'response_code': '\n\nMETADATA = {}\n\n\ndef check(candidate):\n    assert candidate(5) == 4\n    assert candidate(8) == 28\n    assert candidate(10) == 104\n    assert candidate(12) == 386\n\n'}}]

In [32]:
dataset = client_langsmith.list_datasets()

### Avaliando o agente

In [33]:
from langsmith import traceable
from langchain_core.messages import HumanMessage

In [34]:
@traceable
async def agent_avaliado(question):
    answer = await agent.ainvoke(
    {
        "messages": 
            [HumanMessage(role="user",
                          content=question)],
        "todos": [],
    }
)
    return answer['messages'][-1].content

In [35]:
# We'll first define a custom code evaluator, which are useful to measure deterministic or close-ended metrics.
def conciseness(outputs: dict) -> bool:
    words = outputs["output"].split(" ")
    return len(words) <= 200

LLM-as-a-Judge Evaluator
For open-ended metrics, it's can be powerful to use an LLM to score the outputs.

Let's use an LLM to check whether our application produces correct outputs. First, let's define a scoring schema for our LLM to adhere to in its response.

In [36]:
from pydantic import BaseModel, Field

# Define a scoring schema that our LLM must adhere to
class CorrectnessScore(BaseModel):
    """Correctness score of the answer when compared to the reference answer."""
    score: int = Field(description="The score for the correctness of the answer, of an answer between 0 and 1")

In [37]:
#from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage
import asyncio
from pydantic_ai import Agent
from pydantic_ai.models.huggingface import HuggingFaceModel
from pydantic_ai.models.google import GoogleModel
from pydantic_ai.providers.google import GoogleProvider

async def correctness(inputs: dict, outputs: dict, reference_outputs: dict) -> bool:
    prompt = """
    You are an expert data labeler evaluating model outputs for correctness. Your task is to assign a score based on the following rubric:

    <Rubric>
        A correct answer:
        - Provides accurate information
        - Uses suitable analogies and examples
        - Contains no factual errors
        - Is logically consistent

        When scoring, you should penalize:
        - Factual errors
        - Incoherent analogies and examples
        - Logical inconsistencies
    </Rubric>

    <Instructions>
        - Carefully read the input and output
        - Use the reference output to determine if the model output contains errors
        - Focus whether the model output uses accurate analogies and is logically consistent
    </Instructions>

    <Reminder>
        The analogies in the output do not need to match the reference output exactly. Focus on logical consistency.
    </Reminder>

    <input>
        {}
    </input>

    <output>
        {}
    </output>

    Use the reference outputs below to help you evaluate the correctness of the response:
    <reference_outputs>
        {}
    </reference_outputs>
    """.format(inputs["aswer_code"], outputs["output"], reference_outputs["response_code"])

    
    """model = init_chat_model(model = "moonshotai/kimi-k2-instruct-0905", model_provider = "nvidia")
    
    model_stutured = model.with_structured_output(CorrectnessScore)
    
    response = await model_stutured.ainvoke([HumanMessage(content=prompt)])"""
    
    model = GoogleModel('models/gemini-2.0-flash-lite')
    agent = Agent(model, output_type=CorrectnessScore)

    try:
        response = agent.run_sync(prompt)
    except Exception as e:
        logger.error(f"Erro do tipo: {e}")
        model = GoogleModel('models/gemini-2.0-flash')
        agent = Agent(model, output_type=CorrectnessScore)
        response = agent.run_sync(prompt)
    
    if isinstance(response, dict):
        response = response["score"]
    else:
        response = response.output.score
    return response

In [38]:
import nest_asyncio

# Apply nest_asyncio at the start of your notebook
nest_asyncio.apply()

def correctness_sync(inputs: dict, outputs: dict, reference_outputs: dict) -> bool:
    return asyncio.run(correctness(inputs, outputs, reference_outputs))

In [39]:
response = correctness_sync({"aswer_code": "def add(a, b):\n    return a + b"}, {"output": "def add(a, b):\n    return a + b"}, {"response_code": "def add(a, b):\n    return a + b"})

INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"

In [40]:
response

1

In [41]:
# 4. Define a function to run your application
async def run(inputs: dict):
    return await agent_avaliado(inputs["aswer_code"])

In [ ]:
from langsmith import evaluate, aevaluate

modelos = [
    #{"model": "openai/gpt-oss-20b",  "provider": "groq"},
    #{"model": "meta-llama/llama-4-scout-17b-16e-instruct",  "provider": "groq"},
    #{"model": "moonshotai/kimi-k2-instruct-0905",  "provider": "groq"},
    #{"model": "qwen/qwen3-next-80b-a3b-instruct",  "provider": "nvidia"},
    #{"model": "deepseek-ai/deepseek-v3.1",  "provider": "nvidia"},
    #{"model": "microsoft/phi-4-mini-instruct",  "provider": "nvidia"},
    #{"model": "moonshotai/kimi-k2-instruct-0905",  "provider": "nvidia"},
    #{"model": "meta/llama-4-scout-17b-16e-instruct",  "provider": "nvidia"},
    #{"model": "openai/gpt-oss-120b",  "provider": "nvidia"},
    #{"model": "moonshotai/kimi-k2-instruct",  "provider": "nvidia"},
    #{"model": "meta/llama-3.3-70b-instruct",  "provider": "nvidia"},
    #{"model": "nvidia/llama-3.3-nemotron-super-49b-v1.5",  "provider": "nvidia"},
    #{"model": "nvidia/llama-3.1-nemotron-ultra-253b-v1",  "provider": "nvidia"},
    #{"model": "meta/llama-3.1-405b-instruct",  "provider": "nvidia"},
    #{"model": "nvidia/llama-3.1-nemotron-nano-4b-v1.1",  "provider": "nvidia"},
    #{"model": "ibm/granite-3.3-8b-instruct",  "provider": "nvidia"},
    #{"model": "nv-mistralai/mistral-nemo-12b-instruct",  "provider": "nvidia"},
    #{"model": "nvidia/llama-3.3-nemotron-super-49b-v1",  "provider": "nvidia"},
    #{"model": "mistralai/mistral-small-3.1-24b-instruct-2503",  "provider": "nvidia"},
    #{"model": "qwen/qwq-32b",  "provider": "nvidia"},
    #{"model": "meta/llama-3.1-8b-instruct",  "provider": "nvidia"},
    #{"model": "mistralai/mistral-nemotron",  "provider": "nvidia"},
    #{"model": "meta/llama-3.2-3b-instruct",  "provider": "nvidia"},
    {"model": "openai/gpt-oss-20b",  "provider": "nvidia"},
    {"model": "mistralai/mistral-large-2-instruct",  "provider": "nvidia"},
    {"model": "deepseek-ai/deepseek-r1-0528",  "provider": "nvidia"},
    {"model": "meta/llama-3.1-70b-instruct",  "provider": "nvidia"}
    
    
]

models_concluidos = []

for modelo in modelos:
    print(f"Rodando o agente com o modelo {modelo['model']} do provedor {modelo['provider']}")
    
    if modelo['model'] in models_concluidos:
        print("Modelo já concluído")
        continue
    else:
        code_agent = CodeAgentReact(model=modelo['model'], model_provider=modelo['provider'])
        agent = code_agent.create_agent()
        
        @traceable
        async def agent_avaliado(question):
            answer = await agent.ainvoke(
            {
                "messages": 
                    [HumanMessage(role="user",
                                content=question)],
                "todos": [],
            }
        )
            return answer['messages'][-1].content
        
        async def run(inputs: dict):
            return await agent_avaliado(inputs["aswer_code"])
        
        
        results = asyncio.run(aevaluate(
            run,
            data=dataset_name,
            evaluators=[correctness, conciseness],
            experiment_prefix=f"{dataset_name}-{modelo['model']}-{modelo['provider']}"))
        
        models_concluidos.append(modelo['model'])

### Avaliando os resultados

In [42]:
from langsmith import Client
client_langsmith = Client()

In [43]:
experiments_names = [experiment.name for experiment in client_langsmith.list_projects() if "Human-Eval-Code-" in experiment.name]
experiments_names

['Human-Eval-Code-5-aleatorios-moonshotai/kimi-k2-instruct-0905-nvidia-2d202f43',
 'Human-Eval-Code-5-aleatorios-meta/llama-3.1-70b-instruct-nvidia-7e8431d8',
 'Human-Eval-Code-5-aleatorios-deepseek-ai/deepseek-r1-0528-nvidia-17f68b12',
 'Human-Eval-Code-5-aleatorios-mistralai/mistral-large-2-instruct-nvidia-12c3ca39',
 'Human-Eval-Code-5-aleatorios-openai/gpt-oss-20b-nvidia-df66f777',
 'Human-Eval-Code-5-aleatorios-meta/llama-3.2-3b-instruct-nvidia-3d339d56',
 'Human-Eval-Code-5-aleatorios-mistralai/mistral-nemotron-nvidia-44484a26',
 'Human-Eval-Code-5-aleatorios-meta/llama-3.1-8b-instruct-nvidia-5ec1633b',
 'Human-Eval-Code-5-aleatorios-qwen/qwq-32b-nvidia-c5ffcc47',
 'Human-Eval-Code-5-aleatorios-mistralai/mistral-small-3.1-24b-instruct-2503-nvidia-6a6f639d',
 'Human-Eval-Code-5-aleatorios-nvidia/llama-3.3-nemotron-super-49b-v1-nvidia-7ec57602',
 'Human-Eval-Code-5-aleatorios-nv-mistralai/mistral-nemo-12b-instruct-nvidia-68e1ffbc',
 'Human-Eval-Code-5-aleatorios-ibm/granite-3.3-8b-instruct-nvidia-cca74e01',
 'Human-Eval-Code-5-aleatorios-nvidia/llama-3.1-nemotron-nano-4b-v1.1-nvidia-5a8baf83',
 'Human-Eval-Code-5-aleatorios-meta/llama-3.1-405b-instruct-nvidia-5ae2bd1e',
 'Human-Eval-Code-5-aleatorios-nvidia/llama-3.1-nemotron-ultra-253b-v1-nvidia-340e3750',
 'Human-Eval-Code-5-aleatorios-nvidia/llama-3.3-nemotron-super-49b-v1.5-nvidia-eb893acb',
 'Human-Eval-Code-5-aleatorios-meta/llama-3.3-70b-instruct-nvidia-fad4c182',
 'Human-Eval-Code-5-aleatorios-moonshotai/kimi-k2-instruct-nvidia-898fd267',
 'Human-Eval-Code-5-aleatorios-openai/gpt-oss-120b-nvidia-972586a4',
 'Human-Eval-Code-5-aleatorios-meta/llama-4-scout-17b-16e-instruct-nvidia-eb0f3f28',
 'Human-Eval-Code-5-aleatorios-moonshotai/kimi-k2-instruct-0905-nvidia-94cdcbd1',
 'Human-Eval-Code-5-aleatorios-microsoft/phi-4-mini-instruct-nvidia-103a58cc',
 'Human-Eval-Code-5-aleatorios-deepseek-ai/deepseek-v3.1-nvidia-c3468f9f',
 'Human-Eval-Code-5-aleatorios-qwen/qwen3-next-80b-a3b-instruct-nvidia-b6c6da97',
 'Human-Eval-Code-5-aleatorios-moonshotai/kimi-k2-instruct-0905-groq-759669dd',
 'Human-Eval-Code-5-aleatorios-meta-llama/llama-4-scout-17b-16e-instruct-groq-15a85c28',
 'Human-Eval-Code-5-aleatorios-openai/gpt-oss-20b-groq-87adb391']

In [44]:
# Set this to load expt results
for experiment_name in experiments_names:
    print("Loading results for experiment:", experiment_name)
    experiment_results = client_langsmith.read_project(project_name=experiment_name, include_stats=True)
    print("Latency p50:", experiment_results.latency_p50)
    print("Latency p99:", experiment_results.latency_p99)
    print("Token Usage:", experiment_results.total_tokens)
    print("Feedback Stats:", experiment_results.feedback_stats)
    print("*" * 50)

Loading results for experiment: Human-Eval-Code-5-aleatorios-moonshotai/kimi-k2-instruct-0905-nvidia-2d202f43
Latency p50: 0:04:43.158000
Latency p99: 0:04:43.158000
Token Usage: 76945
Feedback Stats: None
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-meta/llama-3.1-70b-instruct-nvidia-7e8431d8
Latency p50: 0:00:29.496000
Latency p99: 0:01:21.206000
Token Usage: 45524
Feedback Stats: {'conciseness': {'n': 5, 'avg': 0.8, 'stdev': 0.39999999999999997, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.4, 'stdev': 0.4898979485566356, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-deepseek-ai/deepseek-r1-0528-nvidia-17f68b12
Latency p50: 0:00:38.971000
Latency p99: 0:02:08.436400
Token Usage: 26395
Feedback Stats: {'conciseness': {'n': 5, 'avg': 0.8, 'stdev': 0.39999999999999997, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.4, 'stdev': 0.4898979485566356, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-mistralai/mistral-large-2-instruct-nvidia-12c3ca39
Latency p50: 0:00:00.624000
Latency p99: 0:00:00.666960
Token Usage: 0
Feedback Stats: {'correctness': {'n': 5, 'avg': 0.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}, 'wrapper': {'n': 5, 'avg': None, 'stdev': None, 'errors': 5, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-openai/gpt-oss-20b-nvidia-df66f777
Latency p50: 0:00:05.628000
Latency p99: 0:00:06.200320
Token Usage: 14060
Feedback Stats: {'conciseness': {'n': 5, 'avg': 1.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-meta/llama-3.2-3b-instruct-nvidia-3d339d56
Latency p50: 0:00:03.444000
Latency p99: 0:00:03.444000
Token Usage: 2693
Feedback Stats: {'conciseness': {'n': 1, 'avg': 1.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 1, 'avg': 0.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-mistralai/mistral-nemotron-nvidia-44484a26
Latency p50: 0:00:03.467000
Latency p99: 0:00:04.817560
Token Usage: 8999
Feedback Stats: {'conciseness': {'n': 5, 'avg': 1.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-meta/llama-3.1-8b-instruct-nvidia-5ec1633b
Latency p50: None
Latency p99: None
Token Usage: 9424
Feedback Stats: None
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-qwen/qwq-32b-nvidia-c5ffcc47
Latency p50: 0:00:02.076000
Latency p99: 0:00:04.337520
Token Usage: 0
Feedback Stats: {'correctness': {'n': 5, 'avg': 0.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}, 'wrapper': {'n': 5, 'avg': None, 'stdev': None, 'errors': 5, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-mistralai/mistral-small-3.1-24b-instruct-2503-nvidia-6a6f639d
Latency p50: 0:00:21.453000
Latency p99: 0:00:23.691280
Token Usage: 10814
Feedback Stats: {'conciseness': {'n': 5, 'avg': 0.2, 'stdev': 0.4, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 1.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-nvidia/llama-3.3-nemotron-super-49b-v1-nvidia-7ec57602
Latency p50: 0:01:45.084000
Latency p99: 0:02:00.089000
Token Usage: 48527
Feedback Stats: {'conciseness': {'n': 5, 'avg': 0.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-nv-mistralai/mistral-nemo-12b-instruct-nvidia-68e1ffbc
Latency p50: 0:02:57.778000
Latency p99: 0:11:58.772120
Token Usage: 109465
Feedback Stats: {'conciseness': {'n': 4, 'avg': 0.75, 'stdev': 0.4330127018922193, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.2, 'stdev': 0.4, 'errors': 0, 'values': {}, 'type': 'primary'}, 'wrapper': {'n': 1, 'avg': None, 'stdev': None, 'errors': 1, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-ibm/granite-3.3-8b-instruct-nvidia-cca74e01
Latency p50: None
Latency p99: None
Token Usage: 749
Feedback Stats: None
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-nvidia/llama-3.1-nemotron-nano-4b-v1.1-nvidia-5a8baf83
Latency p50: 0:00:19.603000
Latency p99: 0:00:39.188280
Token Usage: 17144
Feedback Stats: {'conciseness': {'n': 5, 'avg': 0.2, 'stdev': 0.4, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.6, 'stdev': 0.4898979485566356, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-meta/llama-3.1-405b-instruct-nvidia-5ae2bd1e
Latency p50: 0:02:01.018000
Latency p99: 0:03:57.220120
Token Usage: 52537
Feedback Stats: {'conciseness': {'n': 5, 'avg': 0.6, 'stdev': 0.4898979485566356, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.6, 'stdev': 0.4898979485566356, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-nvidia/llama-3.1-nemotron-ultra-253b-v1-nvidia-340e3750
Latency p50: 0:00:39.179000
Latency p99: 0:00:39.839880
Token Usage: 12683
Feedback Stats: {'conciseness': {'n': 5, 'avg': 0.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 1.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-nvidia/llama-3.3-nemotron-super-49b-v1.5-nvidia-eb893acb
Latency p50: 0:00:16.666000
Latency p99: 0:01:42.162040
Token Usage: 48607
Feedback Stats: {'conciseness': {'n': 5, 'avg': 0.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.8, 'stdev': 0.39999999999999997, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-meta/llama-3.3-70b-instruct-nvidia-fad4c182
Latency p50: 0:01:23.018000
Latency p99: 0:02:06.504280
Token Usage: 57432
Feedback Stats: {'conciseness': {'n': 5, 'avg': 1.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.2, 'stdev': 0.4, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-moonshotai/kimi-k2-instruct-nvidia-898fd267
Latency p50: 0:00:08.037000
Latency p99: 0:00:38.171560
Token Usage: 24903
Feedback Stats: {'conciseness': {'n': 5, 'avg': 1.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-openai/gpt-oss-120b-nvidia-972586a4
Latency p50: 0:00:09.615000
Latency p99: 0:01:38.649320
Token Usage: 49359
Feedback Stats: {'conciseness': {'n': 5, 'avg': 0.8, 'stdev': 0.39999999999999997, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.4, 'stdev': 0.4898979485566356, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-meta/llama-4-scout-17b-16e-instruct-nvidia-eb0f3f28
Latency p50: 0:01:17.804000
Latency p99: 0:01:46.798920
Token Usage: 46849
Feedback Stats: {'conciseness': {'n': 5, 'avg': 0.2, 'stdev': 0.4, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 1.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-moonshotai/kimi-k2-instruct-0905-nvidia-94cdcbd1
Latency p50: 0:03:51.491000
Latency p99: 0:09:08.168720
Token Usage: 296110
Feedback Stats: {'conciseness': {'n': 4, 'avg': 0.75, 'stdev': 0.4330127018922193, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.8, 'stdev': 0.39999999999999997, 'errors': 0, 'values': {}, 'type': 'primary'}, 'wrapper': {'n': 1, 'avg': None, 'stdev': None, 'errors': 1, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-microsoft/phi-4-mini-instruct-nvidia-103a58cc
Latency p50: 0:00:21.119000
Latency p99: 0:00:21.119000
Token Usage: 1805
Feedback Stats: {'conciseness': {'n': 1, 'avg': 1.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 1, 'avg': 0.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-deepseek-ai/deepseek-v3.1-nvidia-c3468f9f
Latency p50: 0:04:00.448000
Latency p99: 0:04:00.448000
Token Usage: 80390
Feedback Stats: {'conciseness': {'n': 1, 'avg': 0.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 1, 'avg': 1.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-qwen/qwen3-next-80b-a3b-instruct-nvidia-b6c6da97
Latency p50: 0:01:34.890000
Latency p99: 0:10:58.090280
Token Usage: 345808
Feedback Stats: {'conciseness': {'n': 4, 'avg': 0.25, 'stdev': 0.4330127018922193, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.8, 'stdev': 0.39999999999999997, 'errors': 0, 'values': {}, 'type': 'primary'}, 'wrapper': {'n': 1, 'avg': None, 'stdev': None, 'errors': 1, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-moonshotai/kimi-k2-instruct-0905-groq-759669dd
Latency p50: 0:01:06.711000
Latency p99: 0:04:24.598360
Token Usage: 117999
Feedback Stats: {'conciseness': {'n': 2, 'avg': 0.5, 'stdev': 0.5, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.6, 'stdev': 0.4898979485566356, 'errors': 0, 'values': {}, 'type': 'primary'}, 'wrapper': {'n': 3, 'avg': None, 'stdev': None, 'errors': 3, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-meta-llama/llama-4-scout-17b-16e-instruct-groq-15a85c28
Latency p50: 0:00:43.891000
Latency p99: 0:01:10.951880
Token Usage: 25491
Feedback Stats: {'conciseness': {'n': 1, 'avg': 0.0, 'stdev': 0.0, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.4, 'stdev': 0.4898979485566356, 'errors': 0, 'values': {}, 'type': 'primary'}, 'wrapper': {'n': 4, 'avg': None, 'stdev': None, 'errors': 4, 'values': {}, 'type': 'primary'}}
**************************************************
Loading results for experiment: Human-Eval-Code-5-aleatorios-openai/gpt-oss-20b-groq-87adb391
Latency p50: 0:01:04.764000
Latency p99: 0:02:29.906760
Token Usage: 72844
Feedback Stats: {'conciseness': {'n': 5, 'avg': 0.6, 'stdev': 0.4898979485566356, 'errors': 0, 'values': {}, 'type': 'primary'}, 'correctness': {'n': 5, 'avg': 0.6, 'stdev': 0.4898979485566356, 'errors': 0, 'values': {}, 'type': 'primary'}}
**************************************************

In [45]:
import pandas as pd
data_frames = pd.DataFrame()
for experiment_name in experiments_names:
    experiment_results = client_langsmith.read_project(project_name=experiment_name, include_stats=True)
    name_column = experiment_name.split("Human-Eval-Code-")[1]
    data = pd.DataFrame.from_dict(experiment_results.dict()).T
    try:
        data_frames[name_column] = data["correctness"]
    except Exception as e:
        print(e)
        pass

'correctness'
'correctness'
'correctness'

In [46]:
data_frames

,5-aleatorios-meta/llama-3.1-70b-instruct-nvidia-7e8431d8,5-aleatorios-deepseek-ai/deepseek-r1-0528-nvidia-17f68b12,5-aleatorios-mistralai/mistral-large-2-instruct-nvidia-12c3ca39,5-aleatorios-openai/gpt-oss-20b-nvidia-df66f777,5-aleatorios-meta/llama-3.2-3b-instruct-nvidia-3d339d56,5-aleatorios-mistralai/mistral-nemotron-nvidia-44484a26,5-aleatorios-qwen/qwq-32b-nvidia-c5ffcc47,5-aleatorios-mistralai/mistral-small-3.1-24b-instruct-2503-nvidia-6a6f639d,5-aleatorios-nvidia/llama-3.3-nemotron-super-49b-v1-nvidia-7ec57602,5-aleatorios-nv-mistralai/mistral-nemo-12b-instruct-nvidia-68e1ffbc,...,5-aleatorios-moonshotai/kimi-k2-instruct-nvidia-898fd267,5-aleatorios-openai/gpt-oss-120b-nvidia-972586a4,5-aleatorios-meta/llama-4-scout-17b-16e-instruct-nvidia-eb0f3f28,5-aleatorios-moonshotai/kimi-k2-instruct-0905-nvidia-94cdcbd1,5-aleatorios-microsoft/phi-4-mini-instruct-nvidia-103a58cc,5-aleatorios-deepseek-ai/deepseek-v3.1-nvidia-c3468f9f,5-aleatorios-qwen/qwen3-next-80b-a3b-instruct-nvidia-b6c6da97,5-aleatorios-moonshotai/kimi-k2-instruct-0905-groq-759669dd,5-aleatorios-meta-llama/llama-4-scout-17b-16e-instruct-groq-15a85c28,5-aleatorios-openai/gpt-oss-20b-groq-87adb391
id,6602d14d-6524-4b44-b436-a2e23b2a8d61,00624a2f-c81a-437d-b29e-46e10b710fe7,99490f67-7191-420e-9cf7-5cb7bb9f38dc,992c20fc-de59-4da1-a92c-11a63a39049a,708b59ee-19af-4c9c-908b-3876f9e651a2,cf1fc542-b503-462e-b7c0-3532175fd4d4,78793346-be81-4829-bdde-8ebd0ab83e28,54079331-7bc8-4a11-8f80-3edae5867b85,fc51cfa7-6465-4e40-8a2e-9581a0162beb,9f722ea2-2480-4c84-97a9-eed451b61a3f,...,92d1d243-ac05-41cf-aa91-651d12e2d20e,d128a1f4-a634-4586-b842-b4fd246c6708,3bf23156-2f77-40ba-82cb-6c2476ef95df,26d48eab-ead5-412a-909c-b66ea3bde1bf,fd5fe5b9-6915-401d-b758-2f3802325580,a3acd42f-e6d8-45b8-90e3-4bbbcd2d68e8,536ee10a-1c28-4d0a-8045-a2ce1f78ea91,e572a9e8-48a6-4fb1-b1cf-3c77e4e0de18,e01c1a84-5d46-4dc1-8f4a-db2b2943821c,3501c9f2-db0a-4f4b-a541-add25988d865
start_time,2025-10-14 16:47:40.476408+00:00,2025-10-14 16:42:42.843531+00:00,2025-10-14 16:42:23.558368+00:00,2025-10-14 16:41:44.626107+00:00,2025-10-14 15:17:42.387629+00:00,2025-10-14 15:16:51.839518+00:00,2025-10-14 14:06:38.415047+00:00,2025-10-14 14:04:32.540711+00:00,2025-10-14 13:53:35.913451+00:00,2025-10-14 13:29:18.356226+00:00,...,2025-10-14 00:50:10.998266+00:00,2025-10-14 00:46:17.308383+00:00,2025-10-14 00:40:46.879063+00:00,2025-10-14 00:19:50.561951+00:00,2025-10-13 17:48:03.618602+00:00,2025-10-13 17:21:32.823472+00:00,2025-10-13 17:03:42.605934+00:00,2025-10-13 16:52:59.349572+00:00,2025-10-13 16:50:00.062808+00:00,2025-10-13 16:43:08.521425+00:00
end_time,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
description,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
name,Human-Eval-Code-5-aleatorios-meta/llama-3.1-70...,Human-Eval-Code-5-aleatorios-deepseek-ai/deeps...,Human-Eval-Code-5-aleatorios-mistralai/mistral...,Human-Eval-Code-5-aleatorios-openai/gpt-oss-20...,Human-Eval-Code-5-aleatorios-meta/llama-3.2-3b...,Human-Eval-Code-5-aleatorios-mistralai/mistral...,Human-Eval-Code-5-aleatorios-qwen/qwq-32b-nvid...,Human-Eval-Code-5-aleatorios-mistralai/mistral...,Human-Eval-Code-5-aleatorios-nvidia/llama-3.3-...,Human-Eval-Code-5-aleatorios-nv-mistralai/mist...,...,Human-Eval-Code-5-aleatorios-moonshotai/kimi-k...,Human-Eval-Code-5-aleatorios-openai/gpt-oss-12...,Human-Eval-Code-5-aleatorios-meta/llama-4-scou...,Human-Eval-Code-5-aleatorios-moonshotai/kimi-k...,Human-Eval-Code-5-aleatorios-microsoft/phi-4-m...,Human-Eval-Code-5-aleatorios-deepseek-ai/deeps...,Human-Eval-Code-5-aleatorios-qwen/qwen3-next-8...,Human-Eval-Code-5-aleatorios-moonshotai/kimi-k...,Human-Eval-Code-5-aleatorios-meta-llama/llama-...,Human-Eval-Code-5-aleatorios-openai/gpt-oss-20...
extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tenant_id,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,...,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87,d9ab5018-45a8-5efd-961d-320c87839c87
reference_dataset_id,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,...,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7,4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7
run_count,5,5,5,5,2,5,5,5,5,5,...,5,5,5,5,2,2,5,5,5,5
latency_p50,0 days 00:00:29.496000,0 days 00:00:38.971000,0 days 00:00:00.624000,0 days 00:00:05.628000,0 days 00:00:03.444000,0 days 00:00:03.467000,0 days 00:00:02.076000,0 days 00:00:21.453000,0 days 00:01:45.084000,0 days 00:02:57.778000,...,0 days 00:00:08.037000,0 days 00:00:09.615000,0 days 00:01:17.804000,0 days 00:03:51.491000,0 days 00:00:21.119000,0 days 00:04:00.448000,0 days 00:01:34.890000,0 days 00:01:06.711000,0 days 00:00:43.891000,0 days 00:01:04.764000
latency_p99,0 days 00:01:21.206000,0 days 00:02:08.436400,0 days 00:00:00.666960,0 days 00:00:06.200320,0 days 00:00:03.444000,0 days 00:00:04.817560,0 days 00:00:04.337520,0 days 00:00:23.691280,0 days 00:02:00.089000,0 days 00:11:58.772120,...,0 days 00:00:38.171560,0 days 00:01:38.649320,0 days 00:01:46.798920,0 days 00:09:08.168720,0 days 00:00:21.119000,0 days 00:04:00.448000,0 days 00:10:58.090280,0 days 00:04:24.598360,0 days 00:01:10.951880,0 days 00:02:29.906760
total_tokens,45524,26395,0,14060,2693,8999,0,10814,48527,109465,...,24903,49359,46849,296110,1805,80390,345808,117999,25491,72844
prompt_tokens,39807,18906,0,9365,2659,8471,0,8471,35866,101820,...,22835,34874,34342,257751,1793,70730,299934,103688,19650,59386
completion_tokens,5717,7489,0,4695,34,528,0,2343,12661,7645,...,2068,14485,12507,38359,12,9660,45874,14311,5841,13458
last_run_start_time,2025-10-14 16:50:09.392391,2025-10-14 16:46:57.880562,2025-10-14 16:42:36.031164,2025-10-14 16:42:13.689561,2025-10-14 15:17:49.666548,2025-10-14 15:17:31.335476,2025-10-14 14:07:14.529949,2025-10-14 14:06:13.956995,2025-10-14 14:03:58.283362,2025-10-14 13:51:09.918225,...,2025-10-14 00:51:01.800555,2025-10-14 00:48:42.740132,2025-10-14 00:45:56.456585,2025-10-14 00:39:28.925023,2025-10-13 17:48:26.544813,2025-10-13 17:25:35.272103,2025-10-13 17:20:20.455838,2025-10-13 17:02:31.372328,2025-10-13 16:52:07.959349,2025-10-13 16:47:41.058610
feedback_stats,"{'n': 5, 'avg': 0.4, 'stdev': 0.48989794855663...","{'n': 5, 'avg': 0.4, 'stdev': 0.48989794855663...","{'n': 5, 'avg': 0.0, 'stdev': 0.0, 'errors': 0...","{'n': 5, 'avg': 0.0, 'stdev': 0.0, 'errors': 0...","{'n': 1, 'avg': 0.0, 'stdev': 0.0, 'errors': 0...","{'n': 5, 'avg': 0.0, 'stdev': 0.0, 'errors': 0...","{'n': 5, 'avg': 0.0, 'stdev': 0.0, 'errors': 0...","{'n': 5, 'avg': 1.0, 'stdev': 0.0, 'errors': 0...","{'n': 5, 'avg': 0.0, 'stdev': 0.0, 'errors': 0...","{'n': 5, 'avg': 0.2, 'stdev': 0.4, 'errors': 0...",...,"{'n': 5, 'avg': 0.0, 'stdev': 0.0, 'errors': 0...","{'n': 5, 'avg': 0.4, 'stdev': 0.48989794855663...","{'n': 5, 'avg': 1.0, 'stdev': 0.0, 'errors': 0...","{'n': 5, 'avg': 0.8, 'stdev': 0.39999999999999...","{'n': 1, 'avg': 0.0, 'stdev': 0.0, 'errors': 0...","{'n': 1, 'avg': 1.0, 'stdev': 0.0, 'errors': 0...","{'n': 5, 'avg': 0.8, 'stdev': 0.39999999999999...","{'n': 5, 'avg': 0.6, 'stdev': 0.48989794855663...","{'n': 5, 'avg': 0.4, 'stdev': 0.48989794855663...","{'n': 5, 'avg': 0.6, 'stdev': 0.48989794855663..."
session_feedback_stats,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
run_facets,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
total_cost,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
prompt_cost,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
completion_cost,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
first_token_p50,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
first_token_p99,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
error_rate,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.2,...,0.0,0.0,0.0,0.2,0.0,0.0,0.2,0.6,0.8,0.0

#### Selecionando os melhores modelos e Testando com mais exemplos

In [47]:
melhores_experiments = [colunas for colunas in data_frames.columns if data_frames[colunas]['feedback_stats']['avg'] > 0.6]
data_frames_melhores = data_frames[melhores_experiments]
data_frames_melhores.head()

,5-aleatorios-mistralai/mistral-small-3.1-24b-instruct-2503-nvidia-6a6f639d,5-aleatorios-nvidia/llama-3.1-nemotron-ultra-253b-v1-nvidia-340e3750,5-aleatorios-nvidia/llama-3.3-nemotron-super-49b-v1.5-nvidia-eb893acb,5-aleatorios-meta/llama-4-scout-17b-16e-instruct-nvidia-eb0f3f28,5-aleatorios-moonshotai/kimi-k2-instruct-0905-nvidia-94cdcbd1,5-aleatorios-deepseek-ai/deepseek-v3.1-nvidia-c3468f9f,5-aleatorios-qwen/qwen3-next-80b-a3b-instruct-nvidia-b6c6da97
id,54079331-7bc8-4a11-8f80-3edae5867b85,9db424b0-ae0a-4ebf-8328-7ec253f76d1b,11c05d0f-b3c9-4de0-b024-1de60dbb7f1c,3bf23156-2f77-40ba-82cb-6c2476ef95df,26d48eab-ead5-412a-909c-b66ea3bde1bf,a3acd42f-e6d8-45b8-90e3-4bbbcd2d68e8,536ee10a-1c28-4d0a-8045-a2ce1f78ea91
start_time,2025-10-14 14:04:32.540711+00:00,2025-10-14 01:01:30.956791+00:00,2025-10-14 00:57:41.016777+00:00,2025-10-14 00:40:46.879063+00:00,2025-10-14 00:19:50.561951+00:00,2025-10-13 17:21:32.823472+00:00,2025-10-13 17:03:42.605934+00:00
end_time,None,None,None,None,None,None,None
description,None,None,None,None,None,None,None
name,Human-Eval-Code-5-aleatorios-mistralai/mistral...,Human-Eval-Code-5-aleatorios-nvidia/llama-3.1-...,Human-Eval-Code-5-aleatorios-nvidia/llama-3.3-...,Human-Eval-Code-5-aleatorios-meta/llama-4-scou...,Human-Eval-Code-5-aleatorios-moonshotai/kimi-k...,Human-Eval-Code-5-aleatorios-deepseek-ai/deeps...,Human-Eval-Code-5-aleatorios-qwen/qwen3-next-8...

In [48]:
melhores_modelos = [{"model":coluna.split('-aleatorios-')[1].rsplit('-', 2)[0], "provedor":coluna.split('-')[-2]} for coluna in data_frames_melhores.columns]

In [49]:
from datasets import load_dataset
from tqdm import tqdm

human_eval = load_dataset("openai_humaneval")['test']

data_set_code_langsmith = []
for problem in tqdm(human_eval, desc="Problems", unit="problem"):
    prompt = problem['prompt']
    test_code = problem['test']
    
    dict_data = {
      "inputs": {"aswer_code": prompt},
      "outputs": {"response_code": test_code},
  }
    
   
    data_set_code_langsmith.append(dict_data)

Problems: 100%|██████████| 164/164 [00:00<00:00, 14256.29problem/s]

In [50]:
from langsmith import Client

client_langsmith = Client()


tamanho_amostra = 15

dataset_name = f"Human-Eval-Code-{tamanho_amostra}-aleatorios"

import random
data_aleatorios = []
index_aleatorios = random.sample(range(len(data_set_code_langsmith)), tamanho_amostra)
for index in index_aleatorios:
    data_aleatorios.append(data_set_code_langsmith[index])


# Create dataset if it doesn't exist
if not client_langsmith.has_dataset(dataset_name=dataset_name):
    dataset = client_langsmith.create_dataset(
        dataset_name=dataset_name, 
        description="The HumanEval dataset released by OpenAI includes 164 programming problems with a function sig- nature, docstring, body, and several unit tests. They were handwritten to ensure not to be included in the training set of code generation models."
    )
    
    client_langsmith.create_examples(dataset_id=dataset.id, examples=data_aleatorios)

In [51]:
experiments_realizados = [experiment.name.split('-aleatorios-')[1].rsplit('-', 2)[0] for experiment in client_langsmith.list_projects() if "Human-Eval-Code-15" in experiment.name]

experiments_realizados

[]

In [ ]:
models_concluidos_melhores = []

for modelo in melhores_modelos:
    print(f"Rodando o agente com o modelo {modelo['model']} do provedor {modelo['provedor']}")
    
    if modelo['model'] in experiments_realizados:
        print("Modelo já concluído")
        continue
    else:
        code_agent = CodeAgentReact(model=modelo['model'], model_provider=modelo['provedor'])
        agent = code_agent.create_agent()
        
        @traceable
        async def agent_avaliado(question):
            answer = await agent.ainvoke(
            {
                "messages": 
                    [HumanMessage(role="user",
                                content=question)],
                "todos": [],
            }
        )
            return answer['messages'][-1].content
        
        async def run(inputs: dict):
            return await agent_avaliado(inputs["aswer_code"])
        
        
        results = asyncio.run(aevaluate(
            run,
            data=dataset_name,
            evaluators=[correctness, conciseness],
            experiment_prefix=f"{dataset_name}-{modelo['model']}-{modelo['provedor']}"))
        
        models_concluidos_melhores.append(modelo['model'])

INFO:code_agent.creat_react_code_agent.code_agent_react:CodeAgentReact inicializado: provider=nvidia, checkpointer=False
INFO:code_agent.creat_react_code_agent.code_agent_react:Modelo provider=nvidia inicializado com sucesso

Rodando o agente com o modelo mistralai/mistral-small-3.1-24b-instruct-2503 do provedor nvidia

INFO:code_agent.creat_react_code_agent.code_agent_react:Agente React criado com sucesso

View the evaluation results for experiment: 'Human-Eval-Code-15-aleatorios-mistralai/mistral-small-3.1-24b-instruct-2503-nvidia-5c8c6900' at:
https://smith.langchain.com/o/d9ab5018-45a8-5efd-961d-320c87839c87/datasets/2129ac60-d387-4965-a732-fdc5e4e27759/compare?selectedSessions=daf0c32e-4e3b-498d-b747-89d81f4d417d

0it [00:00, ?it/s]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
1it [00:26, 26.88s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
2it [00:42, 20.44s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
3it [01:19, 27.64s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
4it [01:43, 26.54s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
5it [02:08, 26.02s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
6it [02:32, 25.08s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
7it [03:01, 26.35s/it]INFO:code_agent.get_routem_llm.routem_llm:Iniciando roteamento LLM
INFO:httpx:HTTP Request: GET https://api.cerebras.ai/v1/tcp_warming "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.cerebras.ai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
ERROR:code_agent.get_routem_llm.router_cerebras:Erro no llm_pydanticai: Error code: 429 - {'message': "We're experiencing high traffic right now! Please try again soon.", 'type': 'too_many_requests_error', 'param': 'queue', 'code': 'queue_exceeded'}
WARNING:code_agent.get_routem_llm.routem_llm:Falha no modelo Groq qwen-3-235b-a22b-instruct-2507: Error code: 429 - {'message': "We're experiencing high traffic right now! Please try again soon.", 'type': 'too_many_requests_error', 'param': 'queue', 'code': 'queue_exceeded'}
INFO:httpx:HTTP Request: GET https://api.cerebras.ai/v1/tcp_warming "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.cerebras.ai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:code_agent.get_routem_llm.routem_llm:Sucesso com modelo Cerebras: gpt-oss-120b
INFO:code_agent.get_routem_llm.routem_llm:Iniciando roteamento LLM
INFO:httpx:HTTP Request: GET https://api.cerebras.ai/v1/tcp_warming "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.cerebras.ai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:code_agent.get_routem_llm.routem_llm:Sucesso com modelo Cerebras: qwen-3-235b-a22b-instruct-2507
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

🤔 AGENTE PENSANDO...
--------------------------------------------------
The user wants a Python function that:
1. Accepts a list of strings.
2. Removes strings whose length is odd.
3. Returns the remaining strings sorted first by length (ascending), then alphabetically if lengths are equal.

The examples given:
- list_sort(["aa", "a", "aaa"]) => ["aa"]
  - "aa" has length 2 (even) → kept
  - "a" and "aaa" have odd lengths → removed
  - Result: ["aa"]

- list_sort(["ab", "a", "aaa", "cd"]) => ["ab", "cd"]
  - "ab" and "cd" have length 2 (even) → kept
  - "a" and "aaa" have odd lengths → removed
  - Sorted by length (all same), then alphabetically → ["ab", "cd"]

Edge cases to consider:
- Empty list → return empty list
- All strings have odd lengths → return empty list
- Duplicates are allowed and should appear as many times as they occur

The provided code is correct and efficient. It uses a list comprehension to filter even-length strings and sorted() with a tuple key (len(x), x) to sort by length then alphabetically. The docstring and test cases are helpful.

The response should:
- Present the final code clearly
- Explain how it works in plain language
- Show how to run it
- Mention that duplicates are preserved and empty lists are handled
- Keep tone friendly and concise
--------------------------------------------------
✅ Análise concluída. Preparando resposta final...

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
8it [04:05, 38.49s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
9it [04:35, 35.67s/it]INFO:code_agent.get_routem_llm.routem_llm:Iniciando roteamento LLM
INFO:httpx:HTTP Request: GET https://api.cerebras.ai/v1/tcp_warming "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.cerebras.ai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:code_agent.get_routem_llm.routem_llm:Sucesso com modelo Cerebras: qwen-3-235b-a22b-instruct-2507
INFO:code_agent.get_routem_llm.routem_llm:Iniciando roteamento LLM
INFO:httpx:HTTP Request: GET https://api.cerebras.ai/v1/tcp_warming "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.cerebras.ai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:code_agent.get_routem_llm.routem_llm:Sucesso com modelo Cerebras: qwen-3-235b-a22b-instruct-2507
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

🤔 AGENTE PENSANDO...
--------------------------------------------------
The user asked for a Python generator that yields Fibonacci numbers up to a given limit. The provided implementation is already clean and correct, but the supervisor pointed out two small issues: (1) the docstring example is ambiguous about whether the limit is inclusive or exclusive, and (2) negative limits currently yield [0], which may be surprising.

To make the answer immediately useful I'll:
- Keep the core generator exactly as written (it's memory-efficient and idiomatic)
- Add a one-line clarification in the docstring that the limit is "inclusive or equal"
- Add a single guard-clause to reject negative limits with a clear ValueError
- Show a quick usage example so the user can copy-paste and run

This keeps the response short, beginner-friendly, and directly addresses the supervisor's suggestions without over-engineering.
--------------------------------------------------
✅ Análise concluída. Preparando resposta final...

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
ERROR:langsmith.evaluation._arunner:Error running target function: [500] Internal Server Error
{'_content': b'Internal Server Error', '_content_consumed': True, '_next': None, 'status_code': 500, 'headers': {'Date': 'Wed, 15 Oct 2025 19:04:33 GMT', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '21', 'Connection': 'keep-alive', 'Access-Control-Expose-Headers': 'nvcf-reqid', 'Nvcf-Reqid': 'dbc390e5-b6ff-48ff-b766-eaef830a24a4', 'Nvcf-Status': 'errored', 'Server': 'uvicorn', 'Vary': 'Origin'}, 'raw': <urllib3.response.HTTPResponse object at 0x000001B9094FABC0>, 'url': 'https://integrate.api.nvidia.com/v1/chat/completions', 'encoding': 'utf-8', 'history': [], 'reason': 'Internal Server Error', 'cookies': <RequestsCookieJar[]>, 'elapsed': datetime.timedelta(microseconds=739592), 'request': <PreparedRequest [POST]>, 'connection': <requests.adapters.HTTPAdapter object at 0x000001B90A969160>}
Traceback (most recent call last):
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langsmith\evaluation\_arunner.py", line 1273, in _aforward
    await fn(*args, langsmith_extra=langsmith_extra)
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langsmith\run_helpers.py", line 552, in async_wrapper
    function_result = await asyncio.create_task(  # type: ignore[call-arg]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 375, in __wakeup
    future.result()
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 304, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langsmith\run_helpers.py", line 549, in run_with_otel_context
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jefer\AppData\Local\Temp\ipykernel_13532\3958114445.py", line 26, in run
    return await agent_avaliado(inputs["aswer_code"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langsmith\run_helpers.py", line 552, in async_wrapper
    function_result = await asyncio.create_task(  # type: ignore[call-arg]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 375, in __wakeup
    future.result()
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 304, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langsmith\run_helpers.py", line 549, in run_with_otel_context
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jefer\AppData\Local\Temp\ipykernel_13532\3958114445.py", line 15, in agent_avaliado
    answer = await agent.ainvoke(
             ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langgraph\pregel\main.py", line 3171, in ainvoke
    async for chunk in self.astream(
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langgraph\pregel\main.py", line 2993, in astream
    async for _ in runner.atick(
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langgraph\pregel\_runner.py", line 295, in atick
    await arun_with_retry(
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langgraph\pregel\_retry.py", line 137, in arun_with_retry
    return await task.proc.ainvoke(task.input, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langgraph\_internal\_runnable.py", line 706, in ainvoke
    input = await asyncio.create_task(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 375, in __wakeup
    future.result()
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 304, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langgraph\_internal\_runnable.py", line 465, in ainvoke
    ret = await asyncio.create_task(coro, context=context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 375, in __wakeup
    future.result()
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 304, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langgraph\prebuilt\chat_agent_executor.py", line 655, in acall_model
    response = cast(AIMessage, await static_model.ainvoke(model_input, config))  # type: ignore[union-attr]
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 3291, in ainvoke
    input_ = await coro_with_context(part(), context, create_task=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 375, in __wakeup
    future.result()
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 304, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 5724, in ainvoke
    return await self.bound.ainvoke(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 417, in ainvoke
    llm_result = await self.agenerate_prompt(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 1036, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 994, in agenerate
    raise exceptions[0]
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 306, in __step_run_and_handle_result
    result = coro.throw(exc)
             ^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 1164, in _agenerate_with_cache
    result = await self._agenerate(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 1224, in _agenerate
    return await run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\runnables\config.py", line 611, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 375, in __wakeup
    future.result()
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\runnables\config.py", line 602, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_nvidia_ai_endpoints\chat_models.py", line 490, in _generate
    response = self._client.get_req(payload=payload, extra_headers=extra_headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_nvidia_ai_endpoints\_common.py", line 500, in get_req
    response, session = self._post(
                        ^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_nvidia_ai_endpoints\_common.py", line 396, in _post
    self._try_raise(response)
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_nvidia_ai_endpoints\_common.py", line 489, in _try_raise
    raise Exception(f"{header}\n{body}") from None
Exception: [500] Internal Server Error
{'_content': b'Internal Server Error', '_content_consumed': True, '_next': None, 'status_code': 500, 'headers': {'Date': 'Wed, 15 Oct 2025 19:04:33 GMT', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '21', 'Connection': 'keep-alive', 'Access-Control-Expose-Headers': 'nvcf-reqid', 'Nvcf-Reqid': 'dbc390e5-b6ff-48ff-b766-eaef830a24a4', 'Nvcf-Status': 'errored', 'Server': 'uvicorn', 'Vary': 'Origin'}, 'raw': <urllib3.response.HTTPResponse object at 0x000001B9094FABC0>, 'url': 'https://integrate.api.nvidia.com/v1/chat/completions', 'encoding': 'utf-8', 'history': [], 'reason': 'Internal Server Error', 'cookies': <RequestsCookieJar[]>, 'elapsed': datetime.timedelta(microseconds=739592), 'request': <PreparedRequest [POST]>, 'connection': <requests.adapters.HTTPAdapter object at 0x000001B90A969160>}
During task with name 'agent' and id '38ead368-9cdb-293e-ba17-2d6d630cf638'
INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
10it [05:13, 36.40s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
11it [05:38, 32.90s/it]

🔍 Searching the web for: how to calculate the strength of an extension based on the number of uppercase and lowercase letters

ERROR:langsmith.evaluation._arunner:Error running target function: [500] Internal Server Error
{'_content': b'Internal Server Error', '_content_consumed': True, '_next': None, 'status_code': 500, 'headers': {'Date': 'Wed, 15 Oct 2025 19:05:12 GMT', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '21', 'Connection': 'keep-alive', 'Access-Control-Expose-Headers': 'nvcf-reqid', 'Nvcf-Reqid': '7605578d-c9ef-46ec-9406-7ccee3d527fc', 'Nvcf-Status': 'errored', 'Server': 'uvicorn', 'Vary': 'Origin'}, 'raw': <urllib3.response.HTTPResponse object at 0x000001B90846C610>, 'url': 'https://integrate.api.nvidia.com/v1/chat/completions', 'encoding': 'utf-8', 'history': [], 'reason': 'Internal Server Error', 'cookies': <RequestsCookieJar[]>, 'elapsed': datetime.timedelta(microseconds=743762), 'request': <PreparedRequest [POST]>, 'connection': <requests.adapters.HTTPAdapter object at 0x000001B9083F4290>}
Traceback (most recent call last):
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langsmith\evaluation\_arunner.py", line 1273, in _aforward
    await fn(*args, langsmith_extra=langsmith_extra)
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langsmith\run_helpers.py", line 552, in async_wrapper
    function_result = await asyncio.create_task(  # type: ignore[call-arg]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 375, in __wakeup
    future.result()
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 304, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langsmith\run_helpers.py", line 549, in run_with_otel_context
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jefer\AppData\Local\Temp\ipykernel_13532\3958114445.py", line 26, in run
    return await agent_avaliado(inputs["aswer_code"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langsmith\run_helpers.py", line 552, in async_wrapper
    function_result = await asyncio.create_task(  # type: ignore[call-arg]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 375, in __wakeup
    future.result()
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 304, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langsmith\run_helpers.py", line 549, in run_with_otel_context
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jefer\AppData\Local\Temp\ipykernel_13532\3958114445.py", line 15, in agent_avaliado
    answer = await agent.ainvoke(
             ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langgraph\pregel\main.py", line 3171, in ainvoke
    async for chunk in self.astream(
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langgraph\pregel\main.py", line 2993, in astream
    async for _ in runner.atick(
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langgraph\pregel\_runner.py", line 295, in atick
    await arun_with_retry(
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langgraph\pregel\_retry.py", line 137, in arun_with_retry
    return await task.proc.ainvoke(task.input, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langgraph\_internal\_runnable.py", line 706, in ainvoke
    input = await asyncio.create_task(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 375, in __wakeup
    future.result()
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 304, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langgraph\_internal\_runnable.py", line 465, in ainvoke
    ret = await asyncio.create_task(coro, context=context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 375, in __wakeup
    future.result()
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 304, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langgraph\prebuilt\chat_agent_executor.py", line 655, in acall_model
    response = cast(AIMessage, await static_model.ainvoke(model_input, config))  # type: ignore[union-attr]
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 3291, in ainvoke
    input_ = await coro_with_context(part(), context, create_task=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 375, in __wakeup
    future.result()
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 304, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\runnables\base.py", line 5724, in ainvoke
    return await self.bound.ainvoke(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 417, in ainvoke
    llm_result = await self.agenerate_prompt(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 1036, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 994, in agenerate
    raise exceptions[0]
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 306, in __step_run_and_handle_result
    result = coro.throw(exc)
             ^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 1164, in _agenerate_with_cache
    result = await self._agenerate(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 1224, in _agenerate
    return await run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\runnables\config.py", line 611, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\tasks.py", line 375, in __wakeup
    future.result()
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\jefer\AppData\Roaming\uv\python\cpython-3.12.0-windows-x86_64-none\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_core\runnables\config.py", line 602, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_nvidia_ai_endpoints\chat_models.py", line 490, in _generate
    response = self._client.get_req(payload=payload, extra_headers=extra_headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_nvidia_ai_endpoints\_common.py", line 500, in get_req
    response, session = self._post(
                        ^^^^^^^^^^^
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_nvidia_ai_endpoints\_common.py", line 396, in _post
    self._try_raise(response)
  File "c:\Users\jefer\Documents\Ciencia-de-dados\LLMs\AgenteCodificaoLangGraph\.venv\Lib\site-packages\langchain_nvidia_ai_endpoints\_common.py", line 489, in _try_raise
    raise Exception(f"{header}\n{body}") from None
Exception: [500] Internal Server Error
{'_content': b'Internal Server Error', '_content_consumed': True, '_next': None, 'status_code': 500, 'headers': {'Date': 'Wed, 15 Oct 2025 19:05:12 GMT', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '21', 'Connection': 'keep-alive', 'Access-Control-Expose-Headers': 'nvcf-reqid', 'Nvcf-Reqid': '7605578d-c9ef-46ec-9406-7ccee3d527fc', 'Nvcf-Status': 'errored', 'Server': 'uvicorn', 'Vary': 'Origin'}, 'raw': <urllib3.response.HTTPResponse object at 0x000001B90846C610>, 'url': 'https://integrate.api.nvidia.com/v1/chat/completions', 'encoding': 'utf-8', 'history': [], 'reason': 'Internal Server Error', 'cookies': <RequestsCookieJar[]>, 'elapsed': datetime.timedelta(microseconds=743762), 'request': <PreparedRequest [POST]>, 'connection': <requests.adapters.HTTPAdapter object at 0x000001B9083F4290>}
During task with name 'agent' and id '8ee83fa3-da4a-7783-8690-bc755585204e'
INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
12it [05:51, 27.10s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
13it [06:11, 24.67s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
14it [06:47, 28.15s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
15it [07:15, 29.01s/it]
INFO:code_agent.creat_react_code_agent.code_agent_react:CodeAgentReact inicializado: provider=nvidia, checkpointer=False
INFO:code_agent.creat_react_code_agent.code_agent_react:Modelo provider=nvidia inicializado com sucesso
INFO:code_agent.creat_react_code_agent.code_agent_react:Agente React criado com sucesso

Rodando o agente com o modelo nvidia/llama-3.1-nemotron-ultra-253b-v1 do provedor nvidia
View the evaluation results for experiment: 'Human-Eval-Code-15-aleatorios-nvidia/llama-3.1-nemotron-ultra-253b-v1-nvidia-c4a815c5' at:
https://smith.langchain.com/o/d9ab5018-45a8-5efd-961d-320c87839c87/datasets/2129ac60-d387-4965-a732-fdc5e4e27759/compare?selectedSessions=13df626a-b607-4c0d-951d-e885e85cf9e9

0it [00:00, ?it/s]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
1it [01:00, 60.62s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
2it [01:39, 47.78s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
3it [02:19, 44.18s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
4it [03:18, 50.29s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
5it [04:20, 54.50s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
6it [05:20, 56.36s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
7it [06:19, 57.03s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
8it [07:19, 58.02s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
9it [08:20, 58.86s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
10it [09:17, 58.52s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
11it [10:15, 58.15s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
12it [11:11, 57.68s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
13it [11:45, 50.40s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
14it [12:42, 52.32s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
15it [13:40, 54.69s/it]
INFO:code_agent.creat_react_code_agent.code_agent_react:CodeAgentReact inicializado: provider=nvidia, checkpointer=False
INFO:code_agent.creat_react_code_agent.code_agent_react:Modelo provider=nvidia inicializado com sucesso
INFO:code_agent.creat_react_code_agent.code_agent_react:Agente React criado com sucesso

Rodando o agente com o modelo nvidia/llama-3.3-nemotron-super-49b-v1.5 do provedor nvidia
View the evaluation results for experiment: 'Human-Eval-Code-15-aleatorios-nvidia/llama-3.3-nemotron-super-49b-v1.5-nvidia-ee714fe4' at:
https://smith.langchain.com/o/d9ab5018-45a8-5efd-961d-320c87839c87/datasets/2129ac60-d387-4965-a732-fdc5e4e27759/compare?selectedSessions=11f1d436-f3d0-4583-bf87-fbcf37477b57

0it [00:00, ?it/s]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
1it [00:16, 16.80s/it]INFO:code_agent.get_routem_llm.routem_llm:Iniciando roteamento LLM
INFO:httpx:HTTP Request: GET https://api.cerebras.ai/v1/tcp_warming "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.cerebras.ai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:code_agent.get_routem_llm.routem_llm:Sucesso com modelo Cerebras: qwen-3-235b-a22b-instruct-2507
INFO:code_agent.get_routem_llm.routem_llm:Iniciando roteamento LLM
INFO:httpx:HTTP Request: GET https://api.cerebras.ai/v1/tcp_warming "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.cerebras.ai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:code_agent.get_routem_llm.routem_llm:Sucesso com modelo Cerebras: qwen-3-235b-a22b-instruct-2507
INFO:code_agent.get_routem_llm.routem_llm:Iniciando roteamento LLM
INFO:httpx:HTTP Request: GET https://api.cerebras.ai/v1/tcp_warming "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.cerebras.ai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:code_agent.get_routem_llm.routem_llm:Sucesso com modelo Cerebras: qwen-3-235b-a22b-instruct-2507
INFO:code_agent.get_routem_llm.routem_llm:Iniciando roteamento LLM
INFO:httpx:HTTP Request: GET https://api.cerebras.ai/v1/tcp_warming "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.cerebras.ai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:code_agent.get_routem_llm.routem_llm:Sucesso com modelo Cerebras: qwen-3-235b-a22b-instruct-2507
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

🤔 AGENTE PENSANDO...
--------------------------------------------------
The user wants me to "implement the max_element function" based on provided doctests. I can see the fully-working implementation and a supervisor review already exist. My job is to package this information into a clear, concise, user-facing response that:

1. Shows the final code in a fenced code block.
2. Briefly explains what the function does and why it’s written this way.
3. Mentions how to run the doctests if the user wants to verify correctness.
4. Keeps the tone friendly and actionable.

No need to alter the code—the supervisor already accepted it. I just need to communicate it effectively.
--------------------------------------------------
✅ Análise concluída. Preparando resposta final...

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
2it [01:34, 52.62s/it]INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent "HTTP/1.1 200 OK"
3it [01:50, 36.08s/it]INFO:code_agent.get_routem_llm.routem_llm:Iniciando roteamento LLM
INFO:httpx:HTTP Request: GET https://api.cerebras.ai/v1/tcp_warming "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.cerebras.ai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:code_agent.get_routem_llm.routem_llm:Sucesso com modelo Cerebras: qwen-3-235b-a22b-instruct-2507
INFO:code_agent.get_routem_llm.routem_llm:Iniciando roteamento LLM
INFO:httpx:HTTP Request: GET https://api.cerebras.ai/v1/tcp_warming "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.cerebras.ai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:code_agent.get_routem_llm.routem_llm:Sucesso com modelo Cerebras: qwen-3-235b-a22b-instruct-2507
INFO:code_agent.get_routem_llm.routem_llm:Iniciando roteamento LLM
INFO:httpx:HTTP Request: GET https://api.cerebras.ai/v1/tcp_warming "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.cerebras.ai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:code_agent.get_routem_llm.routem_llm:Sucesso com modelo Cerebras: qwen-3-235b-a22b-instruct-2507
INFO:code_agent.get_routem_llm.routem_llm:Iniciando roteamento LLM
INFO:httpx:HTTP Request: GET https://api.cerebras.ai/v1/tcp_warming "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.cerebras.ai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:code_agent.get_routem_llm.routem_llm:Sucesso com modelo Cerebras: qwen-3-235b-a22b-instruct-2507
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

🤔 AGENTE PENSANDO...
--------------------------------------------------
The user wants a function to calculate maximum nesting depth of parentheses in space-separated groups. From the inputs, I can see there's already a code implementation that's been reviewed. The supervisor feedback indicates the code needs changes - specifically adding validation to ensure only parentheses characters are present in each group, and potentially making error behavior configurable.

Let me analyze what needs to be implemented:
1. Main function that takes a space-separated string
2. Split into groups by spaces
3. For each group, calculate max nesting depth of parentheses
4. Handle edge cases: empty input, unbalanced parentheses, non-parentheses characters
5. Return list of max depths for each group

The current code has good structure but needs the validation enhancement mentioned in the feedback. I should provide the improved version that includes validation for invalid characters and explain the solution clearly.
--------------------------------------------------
✅ Análise concluída. Preparando resposta final...

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:code_agent.get_routem_llm.routem_llm:Iniciando roteamento LLM
INFO:httpx:HTTP Request: GET https://api.cerebras.ai/v1/tcp_warming "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.cerebras.ai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:code_agent.get_routem_llm.routem_llm:Sucesso com modelo Cerebras: qwen-3-235b-a22b-instruct-2507
INFO:code_agent.get_routem_llm.routem_llm:Iniciando roteamento LLM
INFO:httpx:HTTP Request: GET https://api.cerebras.ai/v1/tcp_warming "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.cerebras.ai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
ERROR:code_agent.get_routem_llm.router_cerebras:Erro no llm_pydanticai: Error code: 429 - {'message': "We're experiencing high traffic right now! Please try again soon.", 'type': 'too_many_requests_error', 'param': 'queue', 'code': 'queue_exceeded'}
WARNING:code_agent.get_routem_llm.routem_llm:Falha no modelo Groq qwen-3-235b-a22b-instruct-2507: Error code: 429 - {'message': "We're experiencing high traffic right now! Please try again soon.", 'type': 'too_many_requests_error', 'param': 'queue', 'code': 'queue_exceeded'}
INFO:httpx:HTTP Request: GET https://api.cerebras.ai/v1/tcp_warming "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.cerebras.ai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:code_agent.get_routem_llm.routem_llm:Sucesso com modelo Cerebras: gpt-oss-120b
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

🤔 AGENTE PENSANDO...
--------------------------------------------------
The user wants me to implement a function that parses nested parentheses and returns the maximum nesting depth. I need to:

1. Create a function called parse_nested_parens that takes a string input
2. Add proper input validation (type checking, character validation, balance checking)
3. Handle invalid characters appropriately
4. Include test cases as shown in the docstring examples
5. Make sure the function raises appropriate exceptions with clear error messages

Looking at the provided code, it already seems to be a complete implementation with all the required features. The code includes:
- Proper docstring with examples
- Type validation (raises TypeError for non-string input)
- Character validation (raises ValueError for invalid characters)
- Balance checking (raises ValueError for unbalanced parentheses)
- Correct algorithm to calculate maximum nesting depth

The implementation looks correct and complete. I should present this to the user with clear explanations of what it does and how to use it, along with the test cases as requested.
--------------------------------------------------
✅ Análise concluída. Preparando resposta final...

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

### Acessando datasets do LangSmith

In [ ]:
# List all datasets
from langsmith import Client

client = Client()

datasets = client.list_datasets()
for dataset in datasets:
    print(dataset.id, dataset.name)

2129ac60-d387-4965-a732-fdc5e4e27759 Human-Eval-Code-15-aleatorios
4dfd7fc2-d782-4c4d-ba17-87f5a251f9a7 Human-Eval-Code-5-aleatorios
b9dd1aaa-017b-4280-96ca-cd6f094773fa deep_research_supervisor_parallelism
5873a0fe-22fd-4a3d-8eb6-86330c26e52f deep_research_agent_termination
2bdcce58-182b-4a36-98a5-74720bc26a05 deep_research_scoping
27916b23-40e0-4874-8d5c-ddbebfcb8958 E-mail Triage Evaluation
b746e978-0744-44de-9f42-6cbd42bbd1e3 agents-from-scratch.test_response
623cff70-db0b-4993-bfe4-6ee88d1a46ac agents-from-scratch.test_tools
a2defcc0-e281-43c6-b351-c7930a9307ac Financial Advisory RAG Evaluation
77fa7a2a-4ece-4096-96fa-ed9d1d9cff81 Healthcare Agent Trajectory Evaluation
43be1111-6a51-4928-a33e-940a33a8b40a Reasoning and Bias
ba1609ff-70a6-4a64-b849-1892bbd24274 QA Example Dataset
aea62e89-af3d-4bb0-98e6-275fd643bfe5 Sample dataset
da848d07-6fa9-4ffe-a503-570e10840ac0 Insurance Claims

In [ ]:
examples = client.list_examples(dataset_id="0b278319-9299-4f5c-8ac3-d068c769469f")
for example in examples:
    print(example.inputs, example.outputs)

LangSmithNotFoundError: Resource not found for /examples. HTTPError('404 Client Error: Not Found for url: https://api.smith.langchain.com/examples?offset=0&inline_s3_urls=True&limit=100&dataset=0b278319-9299-4f5c-8ac3-d068c769469f', '{"detail":"dataset 0b278319-9299-4f5c-8ac3-d068c769469f not found"}')

In [ ]:
experiment_results.dict()

{'id': UUID('e9d43d28-170e-4122-9546-956cf5dec521'),
 'start_time': datetime.datetime(2025, 10, 3, 15, 18, 51, 697051, tzinfo=datetime.timezone.utc),
 'end_time': None,
 'description': None,
 'name': 'test-human-eval-5-qwen/qwen3-next-80b-a3b-instruct-nvidia-dc157e0e',
 'extra': {'metadata': {'git': {'tags': None,
    'dirty': True,
    'branch': 'secundario',
    'commit': '47b18b6248c690a39e12ddf4182201433d49be46',
    'repo_name': 'AgenteCodificaoLangGraph',
    'remote_url': 'https://github.com/Jeferson100/Code-Agent.git',
    'author_name': 'JEFERSON DIONEI SEHNEM',
    'commit_time': '1759163044',
    'author_email': 'sehnemjeferson@gmail.com'},
   'revision_id': '47b18b6-dirty',
   'dataset_splits': ['base'],
   'dataset_version': '2025-10-02T13:48:42.613843+00:00',
   'num_repetitions': 1}},
 'tenant_id': UUID('d9ab5018-45a8-5efd-961d-320c87839c87'),
 'reference_dataset_id': UUID('7556c14d-cd6e-4aaf-9bec-979228fa1f71'),
 'run_count': 5,
 'latency_p50': datetime.timedelta(seconds=83, microseconds=279000),
 'latency_p99': datetime.timedelta(seconds=256, microseconds=879840),
 'total_tokens': 27310,
 'prompt_tokens': 19958,
 'completion_tokens': 7352,
 'last_run_start_time': datetime.datetime(2025, 10, 3, 15, 25, 28, 549023),
 'feedback_stats': {'correctness': {'n': 5,
   'avg': 1.0,
   'stdev': 0.0,
   'errors': 0,
   'values': {},
   'type': 'primary'}},
 'run_facets': None,
 'total_cost': Decimal('0.0'),
 'prompt_cost': Decimal('0.0'),
 'completion_cost': Decimal('0.0'),
 'first_token_p50': None,
 'first_token_p99': None,
 'error_rate': 0.0}